services:
  redis:
    container_name: redis
    hostname: redis
    image: redis
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis:6379
    ports:
    - "8081:8081"
    healthcheck:
      test: [ "CMD", "/redis-commander/bin/healthcheck.js" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  celery_worker:
    build: .
    command: celery -A worker flower --loglevel=info
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy

  client:
    build: .
    command: python client.py
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
      celery_worker:
        condition: service_started

  flower:
    image: mher/flower:latest  # Official Flower image
    command: celery -A worker flower  # Points to your app module 'worker'
    ports:
      - "5555:5555"
    depends_on:
      celery_worker:
        condition: service_started  # Wait for worker to register
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/  # Adjust credentials/URL
      - CELERY_RESULT_BACKEND=redis://redis:6379/0  # Match your Redis setup
volumes:
  rabbitmq_data:
  redis_data: